[package]
name = "black-hole-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
black-hole-shared = { workspace = true }
directories = "6.0"
eframe = { version = "0.35", default-features = false, features = ["wgpu"] }
egui = "0.35"
serde_json = { workspace = true }
tracing = { workspace = true }
winit = "0.30"

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle = "0.6"
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
] }
