[package]
name = "blackhole-daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "blackhole"
path = "src/main.rs"


[build-dependencies]
winresource = "0.1"

[package.metadata.packager]
product-name = "BlackholeIME"
version = "0.1.0"
identifier = "com.blackhole.ime"
description = "Blackhole IME - 跨平台中文输入法"
publisher = "Blackhole IME Team"
copyright = "Copyright (c) 2026 Blackhole IME Team"
formats = ["nsis", "deb", "appimage"]
icons = ["../../assets/icons/blackhole.ico", "../../assets/icons/blackhole.svg"]
resources = ["../../assets/dicts/*"]

[[package.metadata.packager.binaries]]
path = "../../target/release/blackhole"
main = true

[package.metadata.packager.nsis]
template = "../../platforms/windows/installer.nsi"
compression = "lzma"
installer_mode = "perMachine"
languages = ["SimpChinese", "English"]
display_language_selector = false

[package.metadata.packager.deb]
depends = ["ibus"]

[package.metadata.packager.appimage]

[dependencies]
blackhole-engine = { workspace = true }
blackhole-platform = { workspace = true }
blackhole-shared = { workspace = true }
blackhole-ui = { workspace = true }
ctrlc = "3.4"
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
