[package]
name = "black-hole-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "black-hole-cli"
path = "src/main.rs"

[dependencies]
black-hole-shared = { workspace = true }
dirs = "6.0"
lru = "0.12"
pinyin = "0.11"
rime-dict = { git = "https://gitee.com/thelostsoul/rime-dict.git" }
rustc-hash = "2"
self_cell = "1"
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = "3"
